// src/app/pages/admin.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { LucideAngularModule, Settings, Users, MapPin, Trophy, TrendingUp, CheckCircle, XCircle, Package } from 'lucide-angular';

@Component({
    selector: 'app-admin',
    standalone: true,
    imports: [CommonModule, RouterModule, LucideAngularModule],
    template: `
    <div class="min-h-screen bg-background p-4 md:p-6">
      <div class="max-w-7xl mx-auto">
        <div class="mb-8">
          <h1 class="mb-2">Administration</h1>
          <p class="text-muted-foreground">Manage users, fields, and activities</p>
        </div>

        <!-- Stats -->
        <div class="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
          <div class="bg-card rounded-2xl p-6 border border-border">
            <lucide-icon [name]="UsersIcon" [size]="32" class="text-primary mb-2"></lucide-icon>
            <div class="text-3xl font-bold text-primary">10,482</div>
            <div class="text-sm text-muted-foreground">Users</div>
          </div>
          <div class="bg-card rounded-2xl p-6 border border-border">
            <lucide-icon [name]="MapPinIcon" [size]="32" class="text-accent mb-2"></lucide-icon>
            <div class="text-3xl font-bold text-accent">512</div>
            <div class="text-sm text-muted-foreground">Fields</div>
          </div>
          <div class="bg-card rounded-2xl p-6 border border-border">
            <lucide-icon [name]="TrophyIcon" [size]="32" class="text-green-500 mb-2"></lucide-icon>
            <div class="text-3xl font-bold text-green-500">52,341</div>
            <div class="text-sm text-muted-foreground">Matches</div>
          </div>
          <div class="bg-card rounded-2xl p-6 border border-border">
            <lucide-icon [name]="TrendingUpIcon" [size]="32" class="text-primary mb-2"></lucide-icon>
            <div class="text-3xl font-bold">$128k</div>
            <div class="text-sm text-muted-foreground">Revenue</div>
          </div>
        </div>

        <div class="grid lg:grid-cols-3 gap-8">
          <!-- Pending Actions -->
          <div class="lg:col-span-2">
            <div class="bg-card rounded-2xl p-6 border border-border mb-6">
              <h3 class="mb-6">Pending Requests</h3>
              <div class="space-y-4">
                <div *ngFor="let request of pendingRequests" class="flex items-center gap-4 p-4 bg-muted/30 rounded-xl"
                  [ngClass]="request.approved === true ? 'opacity-50' : request.approved === false ? 'opacity-50 line-through' : ''">
                  <div class="w-10 h-10 rounded-full bg-gradient-to-br from-primary to-accent flex items-center justify-center text-primary-foreground font-bold text-sm">
                    {{ request.name.substring(0, 2).toUpperCase() }}
                  </div>
                  <div class="flex-1">
                    <div class="font-semibold text-sm">{{ request.name }}</div>
                    <div class="text-xs text-muted-foreground">{{ request.type }} • {{ request.time }}</div>
                  </div>
                  <div class="flex gap-2" *ngIf="request.approved === null">
                    <button (click)="approveRequest(request)" class="p-2 bg-primary/10 text-primary rounded-lg hover:bg-primary/20 transition-all">
                      <lucide-icon [name]="CheckCircleIcon" [size]="16"></lucide-icon>
                    </button>
                    <button (click)="rejectRequest(request)" class="p-2 bg-destructive/10 text-destructive rounded-lg hover:bg-destructive/20 transition-all">
                      <lucide-icon [name]="XCircleIcon" [size]="16"></lucide-icon>
                    </button>
                  </div>
                  <span *ngIf="request.approved === true" class="text-xs text-green-500 font-semibold">✓ Approved</span>
                  <span *ngIf="request.approved === false" class="text-xs text-destructive font-semibold">✗ Rejected</span>
                </div>
              </div>
            </div>

            <!-- Recent Bookings -->
            <div class="bg-card rounded-2xl p-6 border border-border">
              <h3 class="mb-6">Recent Bookings</h3>
              <div class="overflow-x-auto">
                <table class="w-full text-sm">
                  <thead>
                    <tr class="border-b border-border">
                      <th class="py-2 text-left font-semibold text-muted-foreground">User</th>
                      <th class="py-2 text-left font-semibold text-muted-foreground">Field</th>
                      <th class="py-2 text-left font-semibold text-muted-foreground">Date</th>
                      <th class="py-2 text-left font-semibold text-muted-foreground">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr *ngFor="let booking of recentBookings" class="border-b border-border/50 hover:bg-muted/30 transition-colors">
                      <td class="py-3 font-semibold">{{ booking.user }}</td>
                      <td class="py-3 text-muted-foreground">{{ booking.field }}</td>
                      <td class="py-3 text-muted-foreground">{{ booking.date }}</td>
                      <td class="py-3">
                        <span class="text-xs px-2 py-1 rounded-full font-semibold"
                          [ngClass]="booking.status === 'Confirmed' ? 'bg-primary/10 text-primary' : 'bg-muted text-muted-foreground'">
                          {{ booking.status }}
                        </span>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          <!-- Quick Actions -->
          <div class="space-y-6">
            <div class="bg-card rounded-2xl p-6 border border-border">
              <h3 class="mb-4">Quick Actions</h3>
              <div class="space-y-3">
                <button (click)="router.navigate(['/app/admin/products'])" class="w-full py-3 text-sm bg-accent text-accent-foreground rounded-xl hover:bg-accent/90 transition-all font-semibold shadow-sm text-center">Shop Management (Inventory)</button>
                <button (click)="router.navigate(['/app/admin/badges/dashboard'])" class="w-full py-3 text-sm bg-amber-500 text-white rounded-xl hover:bg-amber-600 transition-all font-semibold">🎖️ Badge Management</button>
                <button (click)="router.navigate(['/app/admin/performances/dashboard'])" class="w-full py-3 text-sm bg-blue-500 text-white rounded-xl hover:bg-blue-600 transition-all font-semibold">📊 Performance Tracking</button>
                <button (click)="router.navigate(['/app/fields/add'])" class="w-full py-3 text-sm bg-primary text-primary-foreground rounded-xl hover:bg-primary/90 transition-all font-semibold">Add a field</button>
                <button (click)="router.navigate(['/app/matches'])" class="w-full py-3 text-sm bg-muted text-foreground font-semibold rounded-xl hover:bg-muted/70 transition-all">Create a tournament</button>
                <button (click)="exportReport()" class="w-full py-3 text-sm border border-border rounded-xl hover:bg-muted transition-all font-semibold">Export reports</button>
              </div>
            </div>
            <div class="bg-card rounded-2xl p-6 border border-border">
              <h3 class="mb-4">System Alerts</h3>
              <div class="space-y-3">
                <div class="flex items-center gap-3 p-3 bg-primary/5 border border-primary/20 rounded-xl">
                  <div class="w-2 h-2 bg-primary rounded-full"></div>
                  <div class="text-sm">12 new users</div>
                </div>
                <div class="flex items-center gap-3 p-3 bg-accent/5 border border-accent/20 rounded-xl">
                  <div class="w-2 h-2 bg-accent rounded-full"></div>
                  <div class="text-sm">3 pending fields</div>
                </div>
                <div class="flex items-center gap-3 p-3 bg-destructive/5 border border-destructive/20 rounded-xl">
                  <div class="w-2 h-2 bg-destructive rounded-full"></div>
                  <div class="text-sm">1 disputed payment</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Toast -->
      <div *ngIf="toast" class="fixed bottom-6 right-6 bg-card border border-border rounded-xl px-4 py-3 shadow-xl text-sm font-medium text-foreground z-50">
        {{ toast }}
      </div>
    </div>
  `,
})
export class AdminComponent {
    readonly UsersIcon = Users;
    readonly MapPinIcon = MapPin;
    readonly TrophyIcon = Trophy;
    readonly TrendingUpIcon = TrendingUp;
    readonly CheckCircleIcon = CheckCircle;
    readonly XCircleIcon = XCircle;

    toast: string | null = null;
    constructor(public router: Router) { }

    pendingRequests: any[] = [
        { name: 'Marc Dupont', type: 'New field', time: '2h ago', approved: null },
        { name: 'Sophie Martin', type: 'Player verification', time: '3h ago', approved: null },
        { name: 'Ahmed Benali', type: 'New field', time: '5h ago', approved: null },
        { name: 'Julie Bernard', type: 'Claim', time: '6h ago', approved: null },
    ];

    recentBookings = [
        { user: 'Alex R.', field: 'Parc Central', date: '10/02/2026', status: 'Confirmed' },
        { user: 'Morgan L.', field: 'Court Premium', date: '12/02/2026', status: 'Confirmed' },
        { user: 'Jordan C.', field: 'Tennis Elite', date: '15/02/2026', status: 'Pending' },
        { user: 'Taylor B.', field: 'Multisport City', date: '18/02/2026', status: 'Confirmed' },
    ];

    approveRequest(req: any) {
        req.approved = true;
        this.showToast(`✅ Request from ${req.name} approved`);
    }

    rejectRequest(req: any) {
        req.approved = false;
        this.showToast(`❌ Request from ${req.name} rejected`);
    }

    exportReport() {
        this.showToast('📊 CSV Export being prepared...');
    }

    showToast(msg: string) {
        this.toast = msg;
        setTimeout(() => this.toast = null, 3000);
    }
}

// src/app/pages/Admin.tsx
import { useState } from "react";
import {
  Users,
  Calendar,
  Package,
  ShoppingBag,
  TrendingUp,
  AlertCircle,
  CheckCircle,
  XCircle,
  MoreVertical,
  Search,
  Filter,
} from "lucide-react";

export function Admin() {
  const [activeTab, setActiveTab] = useState<"users" | "bookings" | "inventory">("users");

  const stats = [
    { label: "Total Users", value: "2,456", change: "+12%", icon: Users, color: "#1DB954" },
    { label: "Active Bookings", value: "342", change: "+8%", icon: Calendar, color: "#F26419" },
    { label: "Inventory Items", value: "1,234", change: "+5%", icon: Package, color: "#06D6A0" },
    { label: "Revenue", value: "$45.2k", change: "+15%", icon: ShoppingBag, color: "#F97316" },
  ];

  const users = [
    { id: 1, name: "Alex Rivera", email: "alex@example.com", role: "Player", status: "active", joinDate: "2025-11-15" },
    { id: 2, name: "Morgan Lee", email: "morgan@example.com", role: "Captain", status: "active", joinDate: "2025-10-20" },
    { id: 3, name: "Jordan Chen", email: "jordan@example.com", role: "Player", status: "inactive", joinDate: "2025-09-12" },
    { id: 4, name: "Taylor Brooks", email: "taylor@example.com", role: "Player", status: "active", joinDate: "2025-12-05" },
    { id: 5, name: "Casey Kim", email: "casey@example.com", role: "Coach", status: "active", joinDate: "2025-08-30" },
  ];

  const bookings = [
    { id: 1, facility: "Central Arena", user: "Alex Rivera", date: "2026-02-05", time: "6:00 PM", status: "confirmed", amount: 45 },
    { id: 2, facility: "Green Field", user: "Morgan Lee", date: "2026-02-06", time: "5:30 PM", status: "pending", amount: 60 },
    { id: 3, facility: "Elite Tennis Club", user: "Jordan Chen", date: "2026-02-07", time: "4:00 PM", status: "confirmed", amount: 35 },
    { id: 4, facility: "Central Arena", user: "Taylor Brooks", date: "2026-02-08", time: "7:00 PM", status: "cancelled", amount: 45 },
  ];

  const inventory = [
    { id: 1, name: "Pro Running Shoes", category: "Footwear", stock: 45, price: 120, status: "in_stock" },
    { id: 2, name: "Training Kit", category: "Apparel", stock: 12, price: 85, status: "low_stock" },
    { id: 3, name: "Performance Apparel", category: "Apparel", stock: 0, price: 95, status: "out_of_stock" },
    { id: 4, name: "Sports Equipment Set", category: "Equipment", stock: 28, price: 150, status: "in_stock" },
  ];

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b border-border bg-card">
        <div className="container mx-auto px-4 py-6 max-w-7xl">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="mb-2">Admin Control Center</h1>
              <p className="text-muted-foreground">
                Manage users, bookings, and e-commerce inventory
              </p>
            </div>
            <div className="flex gap-3">
              <button className="px-4 py-2 bg-muted text-foreground rounded-xl hover:bg-muted/70 transition-all">
                <Filter className="h-5 w-5 inline mr-2" />
                <span className="hidden sm:inline">Filter</span>
              </button>
              <button className="px-4 py-2 bg-primary text-primary-foreground rounded-xl hover:bg-primary/90 transition-all shadow-lg shadow-primary/30">
                Export Data
              </button>
            </div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 py-8 max-w-7xl">
        {/* Stats Grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
          {stats.map((stat) => {
            const Icon = stat.icon;
            return (
              <div
                key={stat.label}
                className="bg-card rounded-2xl p-6 border border-border hover:border-primary/50 transition-all"
              >
                <div className="flex items-center justify-between mb-4">
                  <div
                    className="h-12 w-12 rounded-xl flex items-center justify-center"
                    style={{ backgroundColor: `${stat.color}15` }}
                  >
                    <Icon className="h-6 w-6" style={{ color: stat.color }} />
                  </div>
                  <span className="text-sm font-semibold text-primary bg-primary/10 px-2 py-1 rounded-lg">
                    {stat.change}
                  </span>
                </div>
                <div className="text-3xl font-bold mb-1">{stat.value}</div>
                <div className="text-sm text-muted-foreground">{stat.label}</div>
              </div>
            );
          })}
        </div>

        {/* Tabs */}
        <div className="bg-card rounded-2xl border border-border overflow-hidden">
          <div className="border-b border-border p-2 bg-muted/30">
            <div className="flex gap-2">
              <button
                onClick={() => setActiveTab("users")}
                className={`px-6 py-3 rounded-xl transition-all ${
                  activeTab === "users"
                    ? "bg-primary text-primary-foreground shadow-lg shadow-primary/30"
                    : "text-muted-foreground hover:bg-muted/50"
                }`}
              >
                <Users className="h-4 w-4 inline mr-2" />
                Users
              </button>
              <button
                onClick={() => setActiveTab("bookings")}
                className={`px-6 py-3 rounded-xl transition-all ${
                  activeTab === "bookings"
                    ? "bg-primary text-primary-foreground shadow-lg shadow-primary/30"
                    : "text-muted-foreground hover:bg-muted/50"
                }`}
              >
                <Calendar className="h-4 w-4 inline mr-2" />
                Bookings
              </button>
              <button
                onClick={() => setActiveTab("inventory")}
                className={`px-6 py-3 rounded-xl transition-all ${
                  activeTab === "inventory"
                    ? "bg-primary text-primary-foreground shadow-lg shadow-primary/30"
                    : "text-muted-foreground hover:bg-muted/50"
                }`}
              >
                <Package className="h-4 w-4 inline mr-2" />
                Inventory
              </button>
            </div>
          </div>

          {/* Search Bar */}
          <div className="p-6 border-b border-border">
            <div className="relative">
              <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 h-5 w-5 text-muted-foreground" />
              <input
                type="text"
                placeholder={`Search ${activeTab}...`}
                className="w-full pl-12 pr-4 py-3 bg-muted border border-border rounded-xl focus:border-primary focus:outline-none"
              />
            </div>
          </div>

          {/* Users Table */}
          {activeTab === "users" && (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-muted/30">
                  <tr>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Name</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Email</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Role</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Status</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Join Date</th>
                    <th className="px-6 py-4 text-right text-sm font-semibold">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {users.map((user) => (
                    <tr key={user.id} className="hover:bg-muted/20 transition-all">
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-3">
                          <div className="h-10 w-10 rounded-full bg-gradient-to-br from-primary to-accent flex items-center justify-center text-white font-bold text-sm">
                            {user.name.split(" ").map((n) => n[0]).join("")}
                          </div>
                          <span className="font-semibold">{user.name}</span>
                        </div>
                      </td>
                      <td className="px-6 py-4 text-sm text-muted-foreground">{user.email}</td>
                      <td className="px-6 py-4">
                        <span className="text-xs px-3 py-1 bg-primary/10 text-primary rounded-full">
                          {user.role}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2">
                          {user.status === "active" ? (
                            <CheckCircle className="h-4 w-4 text-primary" />
                          ) : (
                            <XCircle className="h-4 w-4 text-muted-foreground" />
                          )}
                          <span className="text-sm capitalize">{user.status}</span>
                        </div>
                      </td>
                      <td className="px-6 py-4 text-sm text-muted-foreground">{user.joinDate}</td>
                      <td className="px-6 py-4 text-right">
                        <button className="p-2 hover:bg-muted rounded-lg transition-all">
                          <MoreVertical className="h-5 w-5 text-muted-foreground" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Bookings Table */}
          {activeTab === "bookings" && (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-muted/30">
                  <tr>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Facility</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">User</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Date</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Time</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Status</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Amount</th>
                    <th className="px-6 py-4 text-right text-sm font-semibold">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {bookings.map((booking) => (
                    <tr key={booking.id} className="hover:bg-muted/20 transition-all">
                      <td className="px-6 py-4 font-semibold">{booking.facility}</td>
                      <td className="px-6 py-4 text-sm text-muted-foreground">{booking.user}</td>
                      <td className="px-6 py-4 text-sm">{booking.date}</td>
                      <td className="px-6 py-4 text-sm text-muted-foreground">{booking.time}</td>
                      <td className="px-6 py-4">
                        <span
                          className={`text-xs px-3 py-1 rounded-full ${
                            booking.status === "confirmed"
                              ? "bg-primary/10 text-primary"
                              : booking.status === "pending"
                              ? "bg-accent/10 text-accent"
                              : "bg-destructive/10 text-destructive"
                          }`}
                        >
                          {booking.status}
                        </span>
                      </td>
                      <td className="px-6 py-4 font-semibold">${booking.amount}</td>
                      <td className="px-6 py-4 text-right">
                        <button className="p-2 hover:bg-muted rounded-lg transition-all">
                          <MoreVertical className="h-5 w-5 text-muted-foreground" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Inventory Table */}
          {activeTab === "inventory" && (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-muted/30">
                  <tr>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Product</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Category</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Stock</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Price</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold">Status</th>
                    <th className="px-6 py-4 text-right text-sm font-semibold">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {inventory.map((item) => (
                    <tr key={item.id} className="hover:bg-muted/20 transition-all">
                      <td className="px-6 py-4 font-semibold">{item.name}</td>
                      <td className="px-6 py-4 text-sm text-muted-foreground">{item.category}</td>
                      <td className="px-6 py-4">
                        <span
                          className={`font-semibold ${
                            item.stock === 0
                              ? "text-destructive"
                              : item.stock < 15
                              ? "text-accent"
                              : "text-primary"
                          }`}
                        >
                          {item.stock}
                        </span>
                      </td>
                      <td className="px-6 py-4 font-semibold">${item.price}</td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2">
                          {item.status === "in_stock" ? (
                            <CheckCircle className="h-4 w-4 text-primary" />
                          ) : item.status === "low_stock" ? (
                            <AlertCircle className="h-4 w-4 text-accent" />
                          ) : (
                            <XCircle className="h-4 w-4 text-destructive" />
                          )}
                          <span className="text-xs capitalize">
                            {item.status.replace("_", " ")}
                          </span>
                        </div>
                      </td>
                      <td className="px-6 py-4 text-right">
                        <button className="p-2 hover:bg-muted rounded-lg transition-all">
                          <MoreVertical className="h-5 w-5 text-muted-foreground" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Pagination */}
          <div className="p-6 border-t border-border flex items-center justify-between">
            <p className="text-sm text-muted-foreground">
              Showing 1 to {activeTab === "users" ? users.length : activeTab === "bookings" ? bookings.length : inventory.length} entries
            </p>
            <div className="flex gap-2">
              <button className="px-4 py-2 bg-muted text-foreground rounded-lg hover:bg-muted/70 transition-all">
                Previous
              </button>
              <button className="px-4 py-2 bg-primary text-primary-foreground rounded-lg hover:bg-primary/90 transition-all">
                Next
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
