// src/app/pages/admin/AdminLoyalty.tsx
import React, { useEffect, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/app/components/ui/card';
import { Button } from '@/app/components/ui/button';
import { Input } from '@/app/components/ui/input';
import { Label } from '@/app/components/ui/label';
import { Badge } from '@/app/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/app/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/app/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/app/components/ui/dialog';
import { Trophy, Shield, Coins, Plus, Trash2, Edit } from 'lucide-react';
import { loyaltyService } from '@/services/loyaltyService';
import { LoyaltyProgram, LoyaltyTier } from '@/types/loyalty';
import { toast } from 'sonner';

export default function AdminLoyalty() {
  const [programs, setPrograms] = useState<LoyaltyProgram[]>([]);
  const [tiers, setTiers] = useState<LoyaltyTier[]>([]);
  const [selectedProgramId, setSelectedProgramId] = useState<number | null>(null);
  
  // Forms state
  const [isProgramDialogOpen, setIsProgramDialogOpen] = useState(false);
  const [programForm, setProgramForm] = useState<LoyaltyProgram>({ name: '', description: '', pointValue: 10 });
  
  const [isTierDialogOpen, setIsTierDialogOpen] = useState(false);
  const [tierForm, setTierForm] = useState<LoyaltyTier>({ programId: 0, name: '', minPoints: 0, multiplier: 1 });

  const [addPointsForm, setAddPointsForm] = useState({ userId: '', points: '', reason: '' });

  useEffect(() => {
    fetchPrograms();
  }, []);

  useEffect(() => {
    if (selectedProgramId) {
      fetchTiers(selectedProgramId);
    }
  }, [selectedProgramId]);

  const fetchPrograms = async () => {
    try {
      const data = await loyaltyService.getAllPrograms();
      setPrograms(data);
      if (data.length > 0 && !selectedProgramId) {
        setSelectedProgramId(data[0].id!);
      }
    } catch (error) {
      console.error("Failed to fetch programs", error);
    }
  };

  const fetchTiers = async (programId: number) => {
    try {
      const data = await loyaltyService.getTiersByProgram(programId);
      setTiers(data);
    } catch (error) {
      console.error("Failed to fetch tiers", error);
    }
  };

  const handleCreateProgram = async () => {
    try {
      await loyaltyService.createProgram(programForm);
      setIsProgramDialogOpen(false);
      setProgramForm({ name: '', description: '', pointValue: 10 });
      fetchPrograms();
      toast.success('Program created successfully!');
    } catch (error: any) {
      console.error("Failed to create program", error);
      toast.error(error.message || 'Error creating program');
    }
  };

  const handleDeleteProgram = async (id: number) => {
    if(!confirm("Are you sure you want to delete this program?")) return;
    try {
      await loyaltyService.deleteProgram(id);
      fetchPrograms();
      if (selectedProgramId === id) setSelectedProgramId(null);
      toast.success('Program deleted successfully!');
    } catch (error: any) {
      console.error("Failed to delete program", error);
      toast.error(error.message || 'Error deleting program');
    }
  };

  const handleCreateTier = async () => {
    try {
      if (!selectedProgramId) return;
      await loyaltyService.createTier({ ...tierForm, programId: selectedProgramId });
      setIsTierDialogOpen(false);
      setTierForm({ programId: 0, name: '', minPoints: 0, multiplier: 1 });
      fetchTiers(selectedProgramId);
      toast.success('Tier created successfully!');
    } catch (error: any) {
      console.error("Failed to create tier", error);
      toast.error(error.message || 'Error creating tier');
    }
  };

  const handleDeleteTier = async (id: number) => {
    if(!confirm("Are you sure you want to delete this tier?")) return;
    try {
      await loyaltyService.deleteTier(id);
      if (selectedProgramId) fetchTiers(selectedProgramId);
      toast.success('Tier deleted successfully!');
    } catch (error: any) {
      console.error("Failed to delete tier", error);
      toast.error(error.message || 'Error deleting tier');
    }
  };

  const handleAddPoints = async () => {
    try {
      await loyaltyService.addPoints({
        userId: parseInt(addPointsForm.userId),
        points: parseInt(addPointsForm.points),
        reason: addPointsForm.reason
      });
      setAddPointsForm({ userId: '', points: '', reason: '' });
      alert("Points added successfully!");
    } catch (error) {
      console.error("Failed to add points", error);
      alert("Error adding points.");
    }
  };

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      
      <div className="flex justify-between items-center bg-slate-900 text-white p-6 rounded-xl shadow-lg relative overflow-hidden">
        <div className="relative z-10">
          <h1 className="text-3xl font-bold flex items-center gap-2">
            <Shield className="text-primary" /> 
            Administration - Loyalty
          </h1>
          <p className="text-slate-300 mt-1">Manage programs, tiers and distribute points.</p>
        </div>
        <Trophy className="w-24 h-24 absolute right-0 top-1/2 -translate-y-1/2 text-white/5" />
      </div>

      <Tabs defaultValue="programs" className="w-full">
        <TabsList className="grid w-full grid-cols-3 mb-8">
          <TabsTrigger value="programs">Programs</TabsTrigger>
          <TabsTrigger value="tiers">Tiers</TabsTrigger>
          <TabsTrigger value="points">Point Distribution</TabsTrigger>
        </TabsList>
        
        {/* PROGRAMS TAB */}
        <TabsContent value="programs" className="space-y-4">
          <div className="flex justify-between items-center">
            <h2 className="text-2xl font-bold">Active Programs</h2>
            <Dialog open={isProgramDialogOpen} onOpenChange={setIsProgramDialogOpen}>
              <DialogTrigger asChild>
                <Button className="gap-2"><Plus className="w-4 h-4" /> New Program</Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Create a program</DialogTitle>
                </DialogHeader>
                <div className="space-y-4 py-4">
                  <div className="space-y-2">
                    <Label>Name</Label>
                    <Input value={programForm.name} onChange={e => setProgramForm({...programForm, name: e.target.value})} placeholder="Ex: Street League Rewards" />
                  </div>
                  <div className="space-y-2">
                    <Label>Description</Label>
                    <Input value={programForm.description} onChange={e => setProgramForm({...programForm, description: e.target.value})} />
                  </div>
                  <div className="space-y-2">
                    <Label>Point Value (default pts earned)</Label>
                    <Input type="number" value={programForm.pointValue} onChange={e => setProgramForm({...programForm, pointValue: parseInt(e.target.value) || 0})} />
                  </div>
                </div>
                <DialogFooter>
                  <Button variant="outline" onClick={() => setIsProgramDialogOpen(false)}>Cancel</Button>
                  <Button onClick={handleCreateProgram}>Create</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {programs.map(program => (
              <Card key={program.id} className={`border-2 transition-colors cursor-pointer ${selectedProgramId === program.id ? 'border-primary' : 'hover:border-primary/50'}`} onClick={() => setSelectedProgramId(program.id!)}>
                <CardHeader className="pb-2">
                  <div className="flex justify-between items-start">
                    <CardTitle className="text-lg">{program.name}</CardTitle>
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-red-500 hover:bg-red-50 hover:text-red-600" onClick={(e) => { e.stopPropagation(); handleDeleteProgram(program.id!); }}>
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                  <CardDescription>{program.description}</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="text-sm font-medium text-primary">Base value : {program.pointValue} pts</div>
                </CardContent>
              </Card>
            ))}
            {programs.length === 0 && <div className="text-muted-foreground italic">No programs. Create one.</div>}
          </div>
        </TabsContent>

        {/* TIERS TAB */}
        <TabsContent value="tiers" className="space-y-4">
          {!selectedProgramId ? (
            <div className="p-8 text-center border-2 border-dashed rounded-lg text-muted-foreground">
              Please select or create a program in the "Programs" tab first.
            </div>
          ) : (
            <>
              <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold flex items-center gap-2">
                  Tiers for program <Badge variant="secondary">{programs.find(p => p.id === selectedProgramId)?.name}</Badge>
                </h2>
                <Dialog open={isTierDialogOpen} onOpenChange={setIsTierDialogOpen}>
                  <DialogTrigger asChild>
                    <Button className="gap-2"><Plus className="w-4 h-4" /> Add a Tier</Button>
                  </DialogTrigger>
                  <DialogContent>
                    <DialogHeader>
                      <DialogTitle>Create a VIP tier</DialogTitle>
                    </DialogHeader>
                    <div className="space-y-4 py-4">
                      <div className="space-y-2">
                        <Label>Tier Name (ex: GOLD)</Label>
                        <Input value={tierForm.name} onChange={e => setTierForm({...tierForm, name: e.target.value})} placeholder="BRONZE, SILVER, GOLD..." />
                      </div>
                      <div className="space-y-2">
                        <Label>Minimum Points Required</Label>
                        <Input type="number" value={tierForm.minPoints} onChange={e => setTierForm({...tierForm, minPoints: parseInt(e.target.value) || 0})} />
                      </div>
                      <div className="space-y-2">
                        <Label>Point Multiplier (ex: 1.5)</Label>
                        <Input type="number" step="0.1" value={tierForm.multiplier} onChange={e => setTierForm({...tierForm, multiplier: parseFloat(e.target.value) || 1})} />
                      </div>
                    </div>
                    <DialogFooter>
                      <Button variant="outline" onClick={() => setIsTierDialogOpen(false)}>Cancel</Button>
                      <Button onClick={handleCreateTier}>Create</Button>
                    </DialogFooter>
                  </DialogContent>
                </Dialog>
              </div>

              <Card>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Name</TableHead>
                      <TableHead>Minimum Points</TableHead>
                      <TableHead>Multiplier</TableHead>
                      <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {tiers.map(tier => (
                      <TableRow key={tier.id}>
                        <TableCell className="font-bold">{tier.name}</TableCell>
                        <TableCell>{tier.minPoints}</TableCell>
                        <TableCell>x{tier.multiplier}</TableCell>
                        <TableCell className="text-right">
                          <Button variant="ghost" size="icon" className="text-red-500 hover:bg-red-50 hover:text-red-600" onClick={() => handleDeleteTier(tier.id!)}>
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                    {tiers.length === 0 && (
                      <TableRow>
                        <TableCell colSpan={4} className="text-center py-8 text-muted-foreground">No tiers defined for this program.</TableCell>
                      </TableRow>
                    )}
                  </TableBody>
                </Table>
              </Card>
            </>
          )}
        </TabsContent>

        {/* DISTRIBUTE POINTS TAB */}
        <TabsContent value="points" className="max-w-2xl mx-auto mt-8">
          <Card className="border-t-4 border-t-primary shadow-lg">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Coins className="text-yellow-500" />
                Assign Points
              </CardTitle>
              <CardDescription>
                Manually give points to a user (special reward, event, etc.)
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label>User ID</Label>
                <Input type="number" placeholder="User ID" value={addPointsForm.userId} onChange={e => setAddPointsForm({...addPointsForm, userId: e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label>Number of Points</Label>
                <Input type="number" placeholder="Ex: 500" value={addPointsForm.points} onChange={e => setAddPointsForm({...addPointsForm, points: e.target.value})} />
              </div>
              <div className="space-y-2">
                <Label>Reason / Description</Label>
                <Input placeholder="Ex: Summer tournament winner" value={addPointsForm.reason} onChange={e => setAddPointsForm({...addPointsForm, reason: e.target.value})} />
              </div>
              <Button className="w-full mt-4" onClick={handleAddPoints} disabled={!addPointsForm.userId || !addPointsForm.points || !addPointsForm.reason}>
                Distribute points
              </Button>
            </CardContent>
          </Card>
        </TabsContent>

      </Tabs>
    </div>
  );
}

// src/app/pages/admin-loyalty/admin-loyalty.component.ts
﻿import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LoyaltyService } from '../../services/loyalty.service';
import { LoyaltyProgram, LoyaltyTier } from '../../models/loyalty.model';
import { LucideAngularModule, Shield, Trophy, Coins, Plus, Trash2 } from 'lucide-angular';
import { toast } from 'ngx-sonner';

@Component({
  selector: 'app-admin-loyalty',
  standalone: true,
  imports: [CommonModule, FormsModule, LucideAngularModule],
  templateUrl: './admin-loyalty.component.html',
  styles: [`
    .dialog-overlay { background-color: rgba(0, 0, 0, 0.5); }
  `]
})
export class AdminLoyaltyComponent implements OnInit {
  loyaltyService = inject(LoyaltyService);

  // Icons
  ShieldIcon = Shield;
  TrophyIcon = Trophy;
  CoinsIcon = Coins;
  PlusIcon = Plus;
  TrashIcon = Trash2;

  programs = signal<LoyaltyProgram[]>([]);
  tiers = signal<LoyaltyTier[]>([]);
  selectedProgramId = signal<number | null>(null);

  activeTab = signal<'programs' | 'tiers' | 'points'>('programs');

  isProgramDialogOpen = signal(false);
  programForm: LoyaltyProgram = { name: '', description: '', pointsPerCurrencyUnit: 10 };

  isTierDialogOpen = signal(false);
  tierForm: LoyaltyTier = { programId: 0, name: '', minPoints: 0, multiplier: 1 };

  addPointsForm = { userId: '', points: '', reason: '' };

  ngOnInit() {
    this.fetchPrograms();
  }

  fetchPrograms() {
    this.loyaltyService.getAllPrograms().subscribe({
      next: (data) => {
        this.programs.set(data);
        if (data.length > 0 && !this.selectedProgramId()) {
          this.selectedProgramId.set(data[0].id!);
          this.fetchTiers(data[0].id!);
        }
      },
      error: (err) => console.error('Failed to fetch programs', err)
    });
  }

  fetchTiers(programId: number) {
    this.loyaltyService.getTiersByProgram(programId).subscribe({
      next: (data) => this.tiers.set(data),
      error: (err) => console.error('Failed to fetch tiers', err)
    });
  }

  selectProgram(id: number) {
    this.selectedProgramId.set(id);
    this.fetchTiers(id);
  }

  handleCreateProgram() {
    this.loyaltyService.createProgram(this.programForm).subscribe({
      next: () => {
        this.isProgramDialogOpen.set(false);
        this.programForm = { name: '', description: '', pointsPerCurrencyUnit: 10 };
        this.fetchPrograms();
        toast.success('Program created successfully!');
      },
      error: (err) => {
        console.error("Failed to create program", err);
        toast.error(err.message || 'Error creating program');
      }
    });
  }

  handleDeleteProgram(id: number) {
    if(!confirm("Are yor sure yor want to delete this program?")) return;
    this.loyaltyService.deleteProgram(id).subscribe({
      next: () => {
        this.fetchPrograms();
        if (this.selectedProgramId() === id) {
          this.selectedProgramId.set(null);
          this.tiers.set([]);
        }
        toast.success('Program deleted successfully!');
      },
      error: (err) => {
        console.error("Failed to delete program", err);
        toast.error(err.message || 'Error deleting program');
      }
    });
  }

  handleCreateTier() {
    const pId = this.selectedProgramId();
    if (!pId) return;
    
    const payload = { ...this.tierForm, programId: pId };
    this.loyaltyService.createTier(payload).subscribe({
      next: () => {
        this.isTierDialogOpen.set(false);
        this.tierForm = { programId: 0, name: '', minPoints: 0, multiplier: 1 };
        this.fetchTiers(pId);
        toast.success('Tier created successfully!');
      },
      error: (err) => {
        console.error("Failed to create tier", err);
        toast.error(err.message || 'Error creating tier');
      }
    });
  }

  handleDeleteTier(id: number) {
    if(!confirm("Are yor sure yor want to delete this tier?")) return;
    this.loyaltyService.deleteTier(id).subscribe({
      next: () => {
        const pId = this.selectedProgramId();
        if (pId) this.fetchTiers(pId);
        toast.success('Tier deleted successfully!');
      },
      error: (err) => {
        console.error("Failed to delete tier", err);
        toast.error(err.message || 'Error deleting tier');
      }
    });
  }

  handleAddPoints() {
    this.loyaltyService.addPoints({
      userId: parseInt(this.addPointsForm.userId),
      points: parseInt(this.addPointsForm.points),
      reason: this.addPointsForm.reason
    }).subscribe({
      next: () => {
        this.addPointsForm = { userId: '', points: '', reason: '' };
        toast.success("Points added successfully!");
      },
      error: (err) => {
        console.error("Failed to add points", err);
        toast.error("Error adding points.");
      }
    });
  }
}

﻿<div class="p-8 max-w-7xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
  
  <div class="flex justify-between items-center bg-slate-900 text-white p-6 rounded-xl shadow-lg relative overflow-hidden">
    <div class="relative z-10">
      <h1 class="text-3xl font-bold flex items-center gap-2">
        <lucide-icon [name]="ShieldIcon" class="text-primary"></lucide-icon> 
        Administration - Loyalty
      </h1>
      <p class="text-slate-300 mt-1">Manage programs, tiers and distribute points.</p>
    </div>
    <lucide-icon [name]="TrophyIcon" class="w-24 h-24 absolute right-0 top-1/2 -translate-y-1/2 text-white/5"></lucide-icon>
  </div>

  <div class="w-full">
    <div class="grid w-full grid-cols-3 mb-8 bg-muted rounded-md p-1">
      <button class="inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all" [class.bg-background]="activeTab() === 'programs'" [class.shadow-sm]="activeTab() === 'programs'" (click)="activeTab.set('programs')">Programs</button>
      <button class="inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all" [class.bg-background]="activeTab() === 'tiers'" [class.shadow-sm]="activeTab() === 'tiers'" (click)="activeTab.set('tiers')">Tiers</button>
      <button class="inline-flex items-center justify-center whitespace-nowrap rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all" [class.bg-background]="activeTab() === 'points'" [class.shadow-sm]="activeTab() === 'points'" (click)="activeTab.set('points')">Point Distribution</button>
    </div>
    
    <!-- PROGRAMS TAB -->
    <div *ngIf="activeTab() === 'programs'" class="space-y-4">
      <div class="flex justify-between items-center">
        <h2 class="text-2xl font-bold">Active Programs</h2>
        <button class="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:ortline-noe focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-noe disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 gap-2" (click)="isProgramDialogOpen.set(true)">
          <lucide-icon [name]="PlusIcon" class="w-4 h-4"></lucide-icon> New Program
        </button>

        <!-- Dialog -->
        <div *ngIf="isProgramDialogOpen()" class="fixed inset-0 z-50 flex items-center justify-center dialog-overlay">
          <div class="bg-background border rounded-lg shadow-lg max-w-lg w-full p-6">
            <h2 class="text-lg font-semibold leading-noe tracking-tight mb-4">Create a program</h2>
            <div class="space-y-4 py-4">
              <div class="space-y-2">
                <label class="text-sm font-medium leading-noe">Name</label>
                <input [(ngModel)]="programForm.name" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="Ex: Street League Rewards" />
              </div>
              <div class="space-y-2">
                <label class="text-sm font-medium leading-noe">Description</label>
                <input [(ngModel)]="programForm.description" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
              </div>
              <div class="space-y-2">
                <label class="text-sm font-medium leading-noe">Point Value (default pts earned)</label>
                <input type="number" [(ngModel)]="programForm.pointsPerCurrencyUnit" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
              </div>
            </div>
            <div class="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2">
              <button class="inline-flex items-center justify-center rounded-md text-sm font-medium border bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2" (click)="isProgramDialogOpen.set(false)">Cancel</button>
              <button class="inline-flex items-center justify-center rounded-md text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2" (click)="handleCreateProgram()">Create</button>
            </div>
          </div>
        </div>
      </div>

      <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div *ngFor="let program of programs()" class="rounded-xl border bg-card text-card-foreground shadow border-2 transition-colors cursor-pointer" [class.border-primary]="selectedProgramId() === program.id" [class.hover:border-primary/50]="selectedProgramId() !== program.id" (click)="selectProgram(program.id!)">
          <div class="flex flex-col space-y-1.5 p-6 pb-2">
            <div class="flex justify-between items-start">
              <h3 class="font-semibold leading-noe tracking-tight text-lg">{{program.name}}</h3>
              <button class="inline-flex items-center justify-center rounded-md text-sm font-medium hover:bg-red-50 hover:text-red-600 h-8 w-8 text-red-500" (click)="$event.stopPropagation(); handleDeleteProgram(program.id!)">
                <lucide-icon [name]="TrashIcon" class="w-4 h-4"></lucide-icon>
              </button>
            </div>
            <p class="text-sm text-muted-foreground">{{program.description}}</p>
          </div>
          <div class="p-6 pt-0">
            <div class="text-sm font-medium text-primary">Base value : {{program.pointsPerCurrencyUnit}} pts</div>
          </div>
        </div>
        <div *ngIf="programs().length === 0" class="text-muted-foreground italic">No programs. Create one.</div>
      </div>
    </div>

    <!-- TIERS TAB -->
    <div *ngIf="activeTab() === 'tiers'" class="space-y-4">
      <div *ngIf="!selectedProgramId()" class="p-8 text-center border-2 border-dashed rounded-lg text-muted-foreground">
        Please select or create a program in the "Programs" tab first.
      </div>
      <div *ngIf="selectedProgramId()">
        <div class="flex justify-between items-center mb-4">
          <h2 class="text-2xl font-bold flex items-center gap-2">
            Tiers for program <span class="inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold bg-secondary text-secondary-foreground">Program {{selectedProgramId()}}</span>
          </h2>
          <button class="inline-flex items-center justify-center rounded-md text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 gap-2" (click)="isTierDialogOpen.set(true)">
            <lucide-icon [name]="PlusIcon" class="w-4 h-4"></lucide-icon> Add a Tier
          </button>

          <!-- Dialog -->
          <div *ngIf="isTierDialogOpen()" class="fixed inset-0 z-50 flex items-center justify-center dialog-overlay">
            <div class="bg-background border rounded-lg shadow-lg max-w-lg w-full p-6">
              <h2 class="text-lg font-semibold mb-4">Create a VIP tier</h2>
              <div class="space-y-4 py-4">
                <div class="space-y-2">
                  <label class="text-sm font-medium leading-noe">Tier Name (ex: GOLD)</label>
                  <input [(ngModel)]="tierForm.name" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" placeholder="BRONZE, SILVER, GOLD..." />
                </div>
                <div class="space-y-2">
                  <label class="text-sm font-medium leading-noe">Minimum Points Required</label>
                  <input type="number" [(ngModel)]="tierForm.minPoints" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
                </div>
                <div class="space-y-2">
                  <label class="text-sm font-medium leading-noe">Point Multiplier (ex: 1.5)</label>
                  <input type="number" step="0.1" [(ngModel)]="tierForm.multiplier" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
                </div>
              </div>
              <div class="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2">
                <button class="inline-flex items-center justify-center rounded-md text-sm font-medium border bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2" (click)="isTierDialogOpen.set(false)">Cancel</button>
                <button class="inline-flex items-center justify-center rounded-md text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2" (click)="handleCreateTier()">Create</button>
              </div>
            </div>
          </div>
        </div>

        <div class="rounded-xl border bg-card text-card-foreground shadow">
          <div class="relative w-full overflow-auto">
            <table class="w-full caption-bottom text-sm">
              <thead class="[&_tr]:border-b">
                <tr class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
                  <th class="h-10 px-4 text-left align-middle font-medium text-muted-foreground">Name</th>
                  <th class="h-10 px-4 text-left align-middle font-medium text-muted-foreground">Minimum Points</th>
                  <th class="h-10 px-4 text-left align-middle font-medium text-muted-foreground">Multiplier</th>
                  <th class="h-10 px-4 text-right align-middle font-medium text-muted-foreground">Actions</th>
                </tr>
              </thead>
              <tbody class="[&_tr:last-child]:border-0">
                <tr *ngFor="let tier of tiers()" class="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
                  <td class="p-4 align-middle font-bold">{{tier.name}}</td>
                  <td class="p-4 align-middle">{{tier.minPoints}}</td>
                  <td class="p-4 align-middle">x{{tier.multiplier}}</td>
                  <td class="p-4 align-middle text-right">
                    <button class="inline-flex items-center justify-center rounded-md text-sm font-medium hover:bg-red-50 hover:text-red-600 h-8 w-8 text-red-500" (click)="handleDeleteTier(tier.id!)">
                      <lucide-icon [name]="TrashIcon" class="w-4 h-4"></lucide-icon>
                    </button>
                  </td>
                </tr>
                <tr *ngIf="tiers().length === 0">
                  <td colspan="4" class="p-4 align-middle text-center py-8 text-muted-foreground">No tiers defined for this program.</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <!-- DISTRIBUTE POINTS TAB -->
    <div *ngIf="activeTab() === 'points'" class="max-w-2xl mx-auto mt-8">
      <div class="rounded-xl border bg-card text-card-foreground border-t-4 border-t-primary shadow-lg">
        <div class="flex flex-col space-y-1.5 p-6">
          <h3 class="font-semibold leading-noe tracking-tight flex items-center gap-2">
            <lucide-icon [name]="CoinsIcon" class="text-yellow-500"></lucide-icon>
            Assign Points
          </h3>
          <p class="text-sm text-muted-foreground">Manually give points to a user (special reward, event, etc.)</p>
        </div>
        <div class="p-6 pt-0 space-y-4">
          <div class="space-y-2">
            <label class="text-sm font-medium leading-noe">User ID</label>
            <input type="number" placeholder="User ID" [(ngModel)]="addPointsForm.userId" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium leading-noe">Number of Points</label>
            <input type="number" placeholder="Ex: 500" [(ngModel)]="addPointsForm.points" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
          </div>
          <div class="space-y-2">
            <label class="text-sm font-medium leading-noe">Reason / Description</label>
            <input placeholder="Ex: Summer torrnament winner" [(ngModel)]="addPointsForm.reason" class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm" />
          </div>
          <button class="inline-flex items-center justify-center rounded-md text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2 w-full mt-4 disabled:opacity-50" [disabled]="!addPointsForm.userId || !addPointsForm.points || !addPointsForm.reason" (click)="handleAddPoints()">
            Distribute points
          </button>
        </div>
      </div>
    </div>

  </div>
</div>
