// src/app/components/PublicLayout.tsx
import { Outlet, Link, useLocation } from "react-router";
import { Menu, X, Home, Info, Phone, Grid, LogIn } from "lucide-react";
import logoImage from "@/assets/46063177b77ac48f46bc6be9e7b29a63cce56278.png";
import { useState } from "react";

export function PublicLayout() {
  const location = useLocation();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const navItems = [
    { path: "/", icon: Home, label: "Accueil" },
    { path: "/about", icon: Info, label: "À propos" },
    { path: "/browse", icon: Grid, label: "Explorer" },
    { path: "/contact", icon: Phone, label: "Contact" },
  ];

  const isActive = (path: string) => {
    if (path === "/") {
      return location.pathname === "/";
    }
    return location.pathname.startsWith(path);
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-card border-b border-border shadow-sm">
        <div className="max-w-7xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            {/* Logo */}
            <Link to="/" className="flex items-center gap-2">
              <img src={logoImage} alt="StreetLeague" className="h-10 w-auto" />
            </Link>

            {/* Desktop Navigation */}
            <nav className="hidden md:flex items-center gap-2">
              {navItems.map((item) => {
                const Icon = item.icon;
                const active = isActive(item.path);
                return (
                  <Link
                    key={item.path}
                    to={item.path}
                    className={`flex items-center gap-2 px-4 py-2 rounded-xl transition-all ${
                      active
                        ? "bg-primary/10 text-primary font-semibold"
                        : "text-muted-foreground hover:bg-muted hover:text-foreground"
                    }`}
                  >
                    <Icon className="h-4 w-4" />
                    <span>{item.label}</span>
                  </Link>
                );
              })}
            </nav>

            {/* Auth Buttons */}
            <div className="hidden md:flex items-center gap-3">
              <Link
                to="/auth/login"
                className="px-4 py-2 text-foreground hover:text-primary transition-colors font-semibold flex items-center gap-2"
              >
                <LogIn className="h-4 w-4" />
                Connexion
              </Link>
              <Link
                to="/auth/signup"
                className="px-6 py-2 bg-primary text-primary-foreground rounded-xl font-semibold hover:bg-primary/90 transition-all shadow-md hover:shadow-lg"
              >
                S'inscrire
              </Link>
            </div>

            {/* Mobile Menu Button */}
            <button
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="md:hidden p-2 rounded-lg hover:bg-muted transition-all"
            >
              {mobileMenuOpen ? (
                <X className="h-6 w-6" />
              ) : (
                <Menu className="h-6 w-6" />
              )}
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        {mobileMenuOpen && (
          <div className="md:hidden border-t border-border bg-card">
            <nav className="p-4 space-y-2">
              {navItems.map((item) => {
                const Icon = item.icon;
                const active = isActive(item.path);
                return (
                  <Link
                    key={item.path}
                    to={item.path}
                    onClick={() => setMobileMenuOpen(false)}
                    className={`flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${
                      active
                        ? "bg-primary/10 text-primary font-semibold"
                        : "text-muted-foreground hover:bg-muted hover:text-foreground"
                    }`}
                  >
                    <Icon className="h-5 w-5" />
                    <span>{item.label}</span>
                  </Link>
                );
              })}
              <div className="pt-4 border-t border-border space-y-2">
                <Link
                  to="/auth/login"
                  onClick={() => setMobileMenuOpen(false)}
                  className="flex items-center justify-center gap-2 w-full px-4 py-3 text-foreground hover:bg-muted rounded-xl transition-all font-semibold"
                >
                  <LogIn className="h-5 w-5" />
                  Connexion
                </Link>
                <Link
                  to="/auth/signup"
                  onClick={() => setMobileMenuOpen(false)}
                  className="flex items-center justify-center w-full px-4 py-3 bg-primary text-primary-foreground rounded-xl font-semibold hover:bg-primary/90 transition-all"
                >
                  S'inscrire
                </Link>
              </div>
            </nav>
          </div>
        )}
      </header>

      {/* Main Content */}
      <main className="flex-1">
        <Outlet />
      </main>

      {/* Footer */}
      <footer className="bg-secondary text-secondary-foreground py-12 border-t border-border">
        <div className="max-w-7xl mx-auto px-4">
          <div className="grid md:grid-cols-4 gap-8 mb-8">
            <div>
              <h3 className="text-primary mb-4">StreetLeague</h3>
              <p className="text-sm text-muted-foreground">
                L'écosystème sportif amateur premium
              </p>
            </div>
            <div>
              <h4 className="font-semibold mb-4 text-secondary-foreground">Produit</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link to="/browse" className="text-muted-foreground hover:text-primary transition-colors">
                    Explorer
                  </Link>
                </li>
                <li>
                  <Link to="/about" className="text-muted-foreground hover:text-primary transition-colors">
                    Fonctionnalités
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4 text-secondary-foreground">Entreprise</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <Link to="/about" className="text-muted-foreground hover:text-primary transition-colors">
                    À propos
                  </Link>
                </li>
                <li>
                  <Link to="/contact" className="text-muted-foreground hover:text-primary transition-colors">
                    Contact
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h4 className="font-semibold mb-4 text-secondary-foreground">Légal</h4>
              <ul className="space-y-2 text-sm">
                <li>
                  <a href="#" className="text-muted-foreground hover:text-primary transition-colors">
                    Confidentialité
                  </a>
                </li>
                <li>
                  <a href="#" className="text-muted-foreground hover:text-primary transition-colors">
                    Conditions
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div className="border-t border-border/20 pt-8 text-center text-sm text-muted-foreground">
            <p>© 2026 StreetLeague. Tous droits réservés.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}

// src/app/layout/public-layout/public-layout.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet, RouterModule } from '@angular/router';
import { LucideAngularModule, Menu, X, Home, Info, Phone, Grid, LogIn } from 'lucide-angular';

@Component({
    selector: 'app-public-layout',
    standalone: true,
    imports: [CommonModule, RouterOutlet, RouterModule, LucideAngularModule],
    templateUrl: './public-layout.component.html',
})
export class PublicLayoutComponent {
    mobileMenuOpen = false;

    readonly MenuIcon = Menu;
    readonly XIcon = X;
    readonly HomeIcon = Home;
    readonly InfoIcon = Info;
    readonly PhoneIcon = Phone;
    readonly GridIcon = Grid;
    readonly LogInIcon = LogIn;

    navItems = [
        { path: '/', icon: this.HomeIcon, label: 'Accueil' },
        { path: '/about', icon: this.InfoIcon, label: 'À propos' },
        { path: '/browse', icon: this.GridIcon, label: 'Explorer' },
        { path: '/contact', icon: this.PhoneIcon, label: 'Contact' },
    ];

    toggleMobileMenu() {
        this.mobileMenuOpen = !this.mobileMenuOpen;
    }

    closeMobileMenu() {
        this.mobileMenuOpen = false;
    }
}

<div class="min-h-screen bg-background flex flex-col">
  <!-- Header -->
  <header class="sticky top-0 z-50 bg-card border-b border-border shadow-sm">
    <div class="max-w-7xl mx-auto px-4 py-4">
      <div class="flex items-center justify-between">
        <!-- Logo -->
        <a routerLink="/" class="flex items-center gap-2">
          <img src="/logo.png" alt="StreetLeague" class="h-12 w-auto" />
        </a>

        <!-- Desktop Navigation -->
        <nav class="hidden md:flex items-center gap-2">
          <a *ngFor="let item of navItems" [routerLink]="item.path"
            routerLinkActive="bg-primary/10 text-primary font-semibold"
            [routerLinkActiveOptions]="{exact: item.path === '/'}"
            class="flex items-center gap-2 px-4 py-2 rounded-xl transition-all text-muted-foreground hover:bg-muted hover:text-foreground"
            [class.bg-primary/10]="false" [class.text-primary]="false" [class.font-semibold]="false">
            <lucide-icon [img]="item.icon" class="h-4 w-4"></lucide-icon>
            <span>{{ item.label }}</span>
          </a>
        </nav>

        <!-- Auth Buttons -->
        <div class="hidden md:flex items-center gap-3">
          <a routerLink="/auth/login"
            class="px-4 py-2 text-foreground hover:text-primary transition-colors font-semibold flex items-center gap-2">
            <lucide-icon [img]="LogInIcon" class="h-4 w-4"></lucide-icon>
            Connexion
          </a>
          <a routerLink="/auth/signup"
            class="px-6 py-2 bg-primary text-primary-foreground rounded-xl font-semibold hover:bg-primary/90 transition-all shadow-md hover:shadow-lg">
            S'inscrire
          </a>
        </div>

        <!-- Mobile Menu Button -->
        <button (click)="toggleMobileMenu()" class="md:hidden p-2 rounded-lg hover:bg-muted transition-all">
          <lucide-icon *ngIf="mobileMenuOpen" [img]="XIcon" class="h-6 w-6"></lucide-icon>
          <lucide-icon *ngIf="!mobileMenuOpen" [img]="MenuIcon" class="h-6 w-6"></lucide-icon>
        </button>
      </div>
    </div>

    <!-- Mobile Menu -->
    <div *ngIf="mobileMenuOpen" class="md:hidden border-t border-border bg-card">
      <nav class="p-4 space-y-2">
        <a *ngFor="let item of navItems" [routerLink]="item.path"
          routerLinkActive="bg-primary/10 text-primary font-semibold"
          [routerLinkActiveOptions]="{exact: item.path === '/'}" (click)="closeMobileMenu()"
          class="flex items-center gap-3 px-4 py-3 rounded-xl transition-all text-muted-foreground hover:bg-muted hover:text-foreground">
          <lucide-icon [img]="item.icon" class="h-5 w-5"></lucide-icon>
          <span>{{ item.label }}</span>
        </a>
        <div class="pt-4 border-t border-border space-y-2">
          <a routerLink="/auth/login" (click)="closeMobileMenu()"
            class="flex items-center justify-center gap-2 w-full px-4 py-3 text-foreground hover:bg-muted rounded-xl transition-all font-semibold">
            <lucide-icon [img]="LogInIcon" class="h-5 w-5"></lucide-icon>
            Connexion
          </a>
          <a routerLink="/auth/signup" (click)="closeMobileMenu()"
            class="flex items-center justify-center w-full px-4 py-3 bg-primary text-primary-foreground rounded-xl font-semibold hover:bg-primary/90 transition-all">
            S'inscrire
          </a>
        </div>
      </nav>
    </div>
  </header>

  <!-- Main Content -->
  <main class="flex-1">
    <router-outlet></router-outlet>
  </main>

  <!-- Footer -->
  <footer class="bg-secondary text-secondary-foreground py-12 border-t border-border">
    <div class="max-w-7xl mx-auto px-4">
      <div class="grid md:grid-cols-4 gap-8 mb-8">
        <div>
          <img src="/logo.png" alt="StreetLeague" class="h-10 w-auto mb-3" />
          <p class="text-sm text-muted-foreground">
            L'écosystème sportif amateur premium
          </p>
        </div>
        <div>
          <h4 class="font-semibold mb-4 text-secondary-foreground">Produit</h4>
          <ul class="space-y-2 text-sm">
            <li>
              <a routerLink="/browse" class="text-muted-foreground hover:text-primary transition-colors">
                Explorer
              </a>
            </li>
            <li>
              <a routerLink="/about" class="text-muted-foreground hover:text-primary transition-colors">
                Fonctionnalités
              </a>
            </li>
          </ul>
        </div>
        <div>
          <h4 class="font-semibold mb-4 text-secondary-foreground">Entreprise</h4>
          <ul class="space-y-2 text-sm">
            <li>
              <a routerLink="/about" class="text-muted-foreground hover:text-primary transition-colors">
                À propos
              </a>
            </li>
            <li>
              <a routerLink="/contact" class="text-muted-foreground hover:text-primary transition-colors">
                Contact
              </a>
            </li>
          </ul>
        </div>
        <div>
          <h4 class="font-semibold mb-4 text-secondary-foreground">Légal</h4>
          <ul class="space-y-2 text-sm">
            <li>
              <a href="#" class="text-muted-foreground hover:text-primary transition-colors">
                Confidentialité
              </a>
            </li>
            <li>
              <a href="#" class="text-muted-foreground hover:text-primary transition-colors">
                Conditions
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="border-t border-border/20 pt-8 text-center text-sm text-muted-foreground">
        <p>© 2026 StreetLeague. Tous droits réservés.</p>
      </div>
    </div>
  </footer>
</div>
